# Generated by Django 5.0.1 on 2024-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_actiontime_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='actiontime',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
